#############################################################################
# Makefile for building: quimup
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  quimup.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile quimup.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/taglib -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/release/.moc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = quimup1.0.0
DISTDIR = /tmp/Quimup_1.4.4_source/build/release/.obj/unix/quimup1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lmpdclient -ltag -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/release/.obj/unix/

####### Files

SOURCES       = src/main.cpp \
		src/qm_clicklabel.cpp \
		src/qm_clickprogressbar.cpp \
		src/qm_config.cpp \
		src/qm_core.cpp \
		src/qm_mpdcom.cpp \
		src/qm_player.cpp \
		src/qm_scroller.cpp \
		src/qm_trayicon.cpp \
		src/qm_settings.cpp \
		src/qm_browser.cpp \
		src/qm_playlistview.cpp \
		src/qm_libraryview.cpp \
		src/qm_itemlist.cpp \
		src/qm_songinfo.cpp \
		src/qm_streamloader.cpp \
		src/qm_colorpicker.cpp \
		src/qtlocalpeer.cpp \
		src/qtsingleapplication.cpp build/release/.rcc/qrc_quimup.cpp \
		build/release/.moc/moc_qm_clicklabel.cpp \
		build/release/.moc/moc_qm_clickprogressbar.cpp \
		build/release/.moc/moc_qm_core.cpp \
		build/release/.moc/moc_qm_mpdcom.cpp \
		build/release/.moc/moc_qm_player.cpp \
		build/release/.moc/moc_qm_scroller.cpp \
		build/release/.moc/moc_qm_trayicon.cpp \
		build/release/.moc/moc_qm_settings.cpp \
		build/release/.moc/moc_qm_browser.cpp \
		build/release/.moc/moc_qm_playlistview.cpp \
		build/release/.moc/moc_qm_libraryview.cpp \
		build/release/.moc/moc_qm_streamloader.cpp \
		build/release/.moc/moc_qm_colorpicker.cpp \
		build/release/.moc/moc_qtlocalpeer.cpp \
		build/release/.moc/moc_qtsingleapplication.cpp
OBJECTS       = build/release/.obj/unix/main.o \
		build/release/.obj/unix/qm_clicklabel.o \
		build/release/.obj/unix/qm_clickprogressbar.o \
		build/release/.obj/unix/qm_config.o \
		build/release/.obj/unix/qm_core.o \
		build/release/.obj/unix/qm_mpdcom.o \
		build/release/.obj/unix/qm_player.o \
		build/release/.obj/unix/qm_scroller.o \
		build/release/.obj/unix/qm_trayicon.o \
		build/release/.obj/unix/qm_settings.o \
		build/release/.obj/unix/qm_browser.o \
		build/release/.obj/unix/qm_playlistview.o \
		build/release/.obj/unix/qm_libraryview.o \
		build/release/.obj/unix/qm_itemlist.o \
		build/release/.obj/unix/qm_songinfo.o \
		build/release/.obj/unix/qm_streamloader.o \
		build/release/.obj/unix/qm_colorpicker.o \
		build/release/.obj/unix/qtlocalpeer.o \
		build/release/.obj/unix/qtsingleapplication.o \
		build/release/.obj/unix/qrc_quimup.o \
		build/release/.obj/unix/moc_qm_clicklabel.o \
		build/release/.obj/unix/moc_qm_clickprogressbar.o \
		build/release/.obj/unix/moc_qm_core.o \
		build/release/.obj/unix/moc_qm_mpdcom.o \
		build/release/.obj/unix/moc_qm_player.o \
		build/release/.obj/unix/moc_qm_scroller.o \
		build/release/.obj/unix/moc_qm_trayicon.o \
		build/release/.obj/unix/moc_qm_settings.o \
		build/release/.obj/unix/moc_qm_browser.o \
		build/release/.obj/unix/moc_qm_playlistview.o \
		build/release/.obj/unix/moc_qm_libraryview.o \
		build/release/.obj/unix/moc_qm_streamloader.o \
		build/release/.obj/unix/moc_qm_colorpicker.o \
		build/release/.obj/unix/moc_qtlocalpeer.o \
		build/release/.obj/unix/moc_qtsingleapplication.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		quimup.pro src/qm_clicklabel.h \
		src/qm_clickprogressbar.h \
		src/qm_config.h \
		src/qm_core.h \
		src/qm_mpdcom.h \
		src/qm_player.h \
		src/qm_scroller.h \
		src/qm_songinfo.h \
		src/qm_trayicon.h \
		src/qm_widget_ids.h \
		src/qm_settings.h \
		src/qm_browser.h \
		src/qm_playlistview.h \
		src/qm_libraryview.h \
		src/qm_commandlist.h \
		src/qm_itemlist.h \
		src/qm_browser_ids.h \
		src/qm_streamloader.h \
		src/qm_colorpicker.h \
		src/qtlocalpeer.h \
		src/qtsingleapplication.h \
		src/qtlockedfile.h src/main.cpp \
		src/qm_clicklabel.cpp \
		src/qm_clickprogressbar.cpp \
		src/qm_config.cpp \
		src/qm_core.cpp \
		src/qm_mpdcom.cpp \
		src/qm_player.cpp \
		src/qm_scroller.cpp \
		src/qm_trayicon.cpp \
		src/qm_settings.cpp \
		src/qm_browser.cpp \
		src/qm_playlistview.cpp \
		src/qm_libraryview.cpp \
		src/qm_itemlist.cpp \
		src/qm_songinfo.cpp \
		src/qm_streamloader.cpp \
		src/qm_colorpicker.cpp \
		src/qtlocalpeer.cpp \
		src/qtsingleapplication.cpp
QMAKE_TARGET  = quimup
DESTDIR       = 
TARGET        = quimup


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: quimup.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		quimup.pro \
		src/quimup.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile quimup.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
quimup.pro:
src/quimup.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile quimup.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/quimup.qrc $(DISTDIR)/
	$(COPY_FILE) --parents src/qm_clicklabel.h src/qm_clickprogressbar.h src/qm_config.h src/qm_core.h src/qm_mpdcom.h src/qm_player.h src/qm_scroller.h src/qm_songinfo.h src/qm_trayicon.h src/qm_widget_ids.h src/qm_settings.h src/qm_browser.h src/qm_playlistview.h src/qm_libraryview.h src/qm_commandlist.h src/qm_itemlist.h src/qm_browser_ids.h src/qm_streamloader.h src/qm_colorpicker.h src/qtlocalpeer.h src/qtsingleapplication.h src/qtlockedfile.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/qm_clicklabel.cpp src/qm_clickprogressbar.cpp src/qm_config.cpp src/qm_core.cpp src/qm_mpdcom.cpp src/qm_player.cpp src/qm_scroller.cpp src/qm_trayicon.cpp src/qm_settings.cpp src/qm_browser.cpp src/qm_playlistview.cpp src/qm_libraryview.cpp src/qm_itemlist.cpp src/qm_songinfo.cpp src/qm_streamloader.cpp src/qm_colorpicker.cpp src/qtlocalpeer.cpp src/qtsingleapplication.cpp $(DISTDIR)/
	$(COPY_FILE) --parents quimup_nl.ts quimup_cs.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: build/release/.rcc/qrc_quimup.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/release/.rcc/qrc_quimup.cpp
build/release/.rcc/qrc_quimup.cpp: src/quimup.qrc \
		/usr/lib/x86_64-linux-gnu/qt5/bin/rcc \
		src/resources/menu_dir.png \
		src/resources/musdir_ok.png \
		src/resources/st_play.png \
		src/resources/tr_played_reset.png \
		src/resources/tr_playlist.png \
		src/resources/mn_config.png \
		src/resources/tr_plistappend.png \
		src/resources/tr_pointleft.png \
		src/resources/tr_streamplayed.png \
		src/resources/tr_expand2.png \
		src/resources/groove_bg_conn.png \
		src/resources/tr_plistnew.png \
		src/resources/tr_dir.png \
		src/resources/nopic.png \
		src/resources/tr_play.png \
		src/resources/groove_bg_noconn.png \
		src/resources/tr_shuffle.png \
		src/resources/musdir_nocon.png \
		src/resources/tr_repeat.png \
		src/resources/mn_sizer.png \
		src/resources/mn_icon.png \
		src/resources/tr_random.png \
		src/resources/st_stop.png \
		src/resources/tr_trackx.png \
		src/resources/tr_expand1.png \
		src/resources/menu_view.png \
		src/resources/tr_album.png \
		src/resources/mn_next.png \
		src/resources/menu_load.png \
		src/resources/tr_dragdrop.png \
		src/resources/st_playing.png \
		src/resources/tr_redcross.png \
		src/resources/tr_diropen.png \
		src/resources/tr_wait.png \
		src/resources/tr_dotsmall.png \
		src/resources/st_stopped.png \
		src/resources/mn_prev.png \
		src/resources/mn_play.png \
		src/resources/tr_collapse.png \
		src/resources/vol_handle.png \
		src/resources/tr_single.png \
		src/resources/st_pause.png \
		src/resources/tr_check.png \
		src/resources/onair.png \
		src/resources/tr_dot.png \
		src/resources/tr_stop.png \
		src/resources/tr_albumdate.png \
		src/resources/tr_delete.png \
		src/resources/st_idle.png \
		src/resources/st_paused.png \
		src/resources/tr_track.png \
		src/resources/tr_save.png \
		src/resources/tr_albumyear.png \
		src/resources/st_exit.png \
		src/resources/tr_trackplayed.png \
		src/resources/st_noconn.png \
		src/resources/tr_artist.png \
		src/resources/tr_saveselect.png \
		src/resources/tr_options.png \
		src/resources/tr_search.png \
		src/resources/tr_stream.png \
		src/resources/menu_edit.png \
		src/resources/tr_consume.png \
		src/resources/tr_pause.png \
		src/resources/con_dis.png \
		src/resources/con_ok.png \
		src/resources/st_next.png \
		src/resources/tr_genre.png \
		src/resources/tr_pointrite.png \
		src/resources/groove_sub_play.png \
		src/resources/tr_trackx_played.png \
		src/resources/mn_stop.png \
		src/resources/mn_playlist.png \
		src/resources/tr_playlistplus.png \
		src/resources/mn_pause.png \
		src/resources/tr_xfade.png \
		src/resources/st_prev.png \
		src/resources/musdir_error.png \
		src/resources/tr_purge.png \
		src/resources/tr_update.png
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name quimup src/quimup.qrc -o build/release/.rcc/qrc_quimup.cpp

compiler_moc_header_make_all: build/release/.moc/moc_qm_clicklabel.cpp build/release/.moc/moc_qm_clickprogressbar.cpp build/release/.moc/moc_qm_core.cpp build/release/.moc/moc_qm_mpdcom.cpp build/release/.moc/moc_qm_player.cpp build/release/.moc/moc_qm_scroller.cpp build/release/.moc/moc_qm_trayicon.cpp build/release/.moc/moc_qm_settings.cpp build/release/.moc/moc_qm_browser.cpp build/release/.moc/moc_qm_playlistview.cpp build/release/.moc/moc_qm_libraryview.cpp build/release/.moc/moc_qm_streamloader.cpp build/release/.moc/moc_qm_colorpicker.cpp build/release/.moc/moc_qtlocalpeer.cpp build/release/.moc/moc_qtsingleapplication.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/release/.moc/moc_qm_clicklabel.cpp build/release/.moc/moc_qm_clickprogressbar.cpp build/release/.moc/moc_qm_core.cpp build/release/.moc/moc_qm_mpdcom.cpp build/release/.moc/moc_qm_player.cpp build/release/.moc/moc_qm_scroller.cpp build/release/.moc/moc_qm_trayicon.cpp build/release/.moc/moc_qm_settings.cpp build/release/.moc/moc_qm_browser.cpp build/release/.moc/moc_qm_playlistview.cpp build/release/.moc/moc_qm_libraryview.cpp build/release/.moc/moc_qm_streamloader.cpp build/release/.moc/moc_qm_colorpicker.cpp build/release/.moc/moc_qtlocalpeer.cpp build/release/.moc/moc_qtsingleapplication.cpp
build/release/.moc/moc_qm_clicklabel.cpp: src/qm_clicklabel.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Quimup_1.4.4_source -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/qm_clicklabel.h -o build/release/.moc/moc_qm_clicklabel.cpp

build/release/.moc/moc_qm_clickprogressbar.cpp: src/qm_clickprogressbar.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Quimup_1.4.4_source -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/qm_clickprogressbar.h -o build/release/.moc/moc_qm_clickprogressbar.cpp

build/release/.moc/moc_qm_core.cpp: src/qm_player.h \
		src/qm_clicklabel.h \
		src/qm_clickprogressbar.h \
		src/qm_config.h \
		src/qm_mpdcom.h \
		src/qm_songinfo.h \
		src/qm_itemlist.h \
		src/qm_commandlist.h \
		src/qm_trayicon.h \
		src/qm_widget_ids.h \
		src/qm_scroller.h \
		src/qm_settings.h \
		src/qm_colorpicker.h \
		src/qm_browser.h \
		src/qm_browser_ids.h \
		src/qm_playlistview.h \
		src/qm_libraryview.h \
		src/qm_streamloader.h \
		src/qm_core.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Quimup_1.4.4_source -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/qm_core.h -o build/release/.moc/moc_qm_core.cpp

build/release/.moc/moc_qm_mpdcom.cpp: src/qm_config.h \
		src/qm_songinfo.h \
		src/qm_itemlist.h \
		src/qm_commandlist.h \
		src/qm_mpdcom.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Quimup_1.4.4_source -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/qm_mpdcom.h -o build/release/.moc/moc_qm_mpdcom.cpp

build/release/.moc/moc_qm_player.cpp: src/qm_clicklabel.h \
		src/qm_clickprogressbar.h \
		src/qm_config.h \
		src/qm_mpdcom.h \
		src/qm_songinfo.h \
		src/qm_itemlist.h \
		src/qm_commandlist.h \
		src/qm_trayicon.h \
		src/qm_widget_ids.h \
		src/qm_scroller.h \
		src/qm_settings.h \
		src/qm_colorpicker.h \
		src/qm_browser.h \
		src/qm_browser_ids.h \
		src/qm_playlistview.h \
		src/qm_libraryview.h \
		src/qm_streamloader.h \
		src/qm_player.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Quimup_1.4.4_source -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/qm_player.h -o build/release/.moc/moc_qm_player.cpp

build/release/.moc/moc_qm_scroller.cpp: src/qm_scroller.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Quimup_1.4.4_source -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/qm_scroller.h -o build/release/.moc/moc_qm_scroller.cpp

build/release/.moc/moc_qm_trayicon.cpp: src/qm_widget_ids.h \
		src/qm_mpdcom.h \
		src/qm_config.h \
		src/qm_songinfo.h \
		src/qm_itemlist.h \
		src/qm_commandlist.h \
		src/qm_trayicon.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Quimup_1.4.4_source -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/qm_trayicon.h -o build/release/.moc/moc_qm_trayicon.cpp

build/release/.moc/moc_qm_settings.cpp: src/qm_config.h \
		src/qm_mpdcom.h \
		src/qm_songinfo.h \
		src/qm_itemlist.h \
		src/qm_commandlist.h \
		src/qm_colorpicker.h \
		src/qm_settings.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Quimup_1.4.4_source -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/qm_settings.h -o build/release/.moc/moc_qm_settings.cpp

build/release/.moc/moc_qm_browser.cpp: src/qm_config.h \
		src/qm_browser_ids.h \
		src/qm_playlistview.h \
		src/qm_songinfo.h \
		src/qm_mpdcom.h \
		src/qm_itemlist.h \
		src/qm_commandlist.h \
		src/qm_libraryview.h \
		src/qm_streamloader.h \
		src/qm_browser.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Quimup_1.4.4_source -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/qm_browser.h -o build/release/.moc/moc_qm_browser.cpp

build/release/.moc/moc_qm_playlistview.cpp: src/qm_songinfo.h \
		src/qm_mpdcom.h \
		src/qm_config.h \
		src/qm_itemlist.h \
		src/qm_commandlist.h \
		src/qm_browser_ids.h \
		src/qm_playlistview.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Quimup_1.4.4_source -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/qm_playlistview.h -o build/release/.moc/moc_qm_playlistview.cpp

build/release/.moc/moc_qm_libraryview.cpp: src/qm_songinfo.h \
		src/qm_mpdcom.h \
		src/qm_config.h \
		src/qm_itemlist.h \
		src/qm_commandlist.h \
		src/qm_browser_ids.h \
		src/qm_libraryview.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Quimup_1.4.4_source -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/qm_libraryview.h -o build/release/.moc/moc_qm_libraryview.cpp

build/release/.moc/moc_qm_streamloader.cpp: src/qm_streamloader.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Quimup_1.4.4_source -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/qm_streamloader.h -o build/release/.moc/moc_qm_streamloader.cpp

build/release/.moc/moc_qm_colorpicker.cpp: src/qm_colorpicker.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Quimup_1.4.4_source -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/qm_colorpicker.h -o build/release/.moc/moc_qm_colorpicker.cpp

build/release/.moc/moc_qtlocalpeer.cpp: src/qtlockedfile.h \
		src/qtlocalpeer.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Quimup_1.4.4_source -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/qtlocalpeer.h -o build/release/.moc/moc_qtlocalpeer.cpp

build/release/.moc/moc_qtsingleapplication.cpp: src/qtsingleapplication.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/tmp/Quimup_1.4.4_source -I/usr/include/taglib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/qtsingleapplication.h -o build/release/.moc/moc_qtsingleapplication.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

build/release/.obj/unix/main.o: src/main.cpp src/qtsingleapplication.h \
		src/qm_core.h \
		src/qm_player.h \
		src/qm_clicklabel.h \
		src/qm_clickprogressbar.h \
		src/qm_config.h \
		src/qm_mpdcom.h \
		src/qm_songinfo.h \
		src/qm_itemlist.h \
		src/qm_commandlist.h \
		src/qm_trayicon.h \
		src/qm_widget_ids.h \
		src/qm_scroller.h \
		src/qm_settings.h \
		src/qm_colorpicker.h \
		src/qm_browser.h \
		src/qm_browser_ids.h \
		src/qm_playlistview.h \
		src/qm_libraryview.h \
		src/qm_streamloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/main.o src/main.cpp

build/release/.obj/unix/qm_clicklabel.o: src/qm_clicklabel.cpp src/qm_clicklabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qm_clicklabel.o src/qm_clicklabel.cpp

build/release/.obj/unix/qm_clickprogressbar.o: src/qm_clickprogressbar.cpp src/qm_clickprogressbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qm_clickprogressbar.o src/qm_clickprogressbar.cpp

build/release/.obj/unix/qm_config.o: src/qm_config.cpp src/qm_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qm_config.o src/qm_config.cpp

build/release/.obj/unix/qm_core.o: src/qm_core.cpp src/qm_core.h \
		src/qm_player.h \
		src/qm_clicklabel.h \
		src/qm_clickprogressbar.h \
		src/qm_config.h \
		src/qm_mpdcom.h \
		src/qm_songinfo.h \
		src/qm_itemlist.h \
		src/qm_commandlist.h \
		src/qm_trayicon.h \
		src/qm_widget_ids.h \
		src/qm_scroller.h \
		src/qm_settings.h \
		src/qm_colorpicker.h \
		src/qm_browser.h \
		src/qm_browser_ids.h \
		src/qm_playlistview.h \
		src/qm_libraryview.h \
		src/qm_streamloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qm_core.o src/qm_core.cpp

build/release/.obj/unix/qm_mpdcom.o: src/qm_mpdcom.cpp src/qm_mpdcom.h \
		src/qm_config.h \
		src/qm_songinfo.h \
		src/qm_itemlist.h \
		src/qm_commandlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qm_mpdcom.o src/qm_mpdcom.cpp

build/release/.obj/unix/qm_player.o: src/qm_player.cpp src/qm_player.h \
		src/qm_clicklabel.h \
		src/qm_clickprogressbar.h \
		src/qm_config.h \
		src/qm_mpdcom.h \
		src/qm_songinfo.h \
		src/qm_itemlist.h \
		src/qm_commandlist.h \
		src/qm_trayicon.h \
		src/qm_widget_ids.h \
		src/qm_scroller.h \
		src/qm_settings.h \
		src/qm_colorpicker.h \
		src/qm_browser.h \
		src/qm_browser_ids.h \
		src/qm_playlistview.h \
		src/qm_libraryview.h \
		src/qm_streamloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qm_player.o src/qm_player.cpp

build/release/.obj/unix/qm_scroller.o: src/qm_scroller.cpp src/qm_scroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qm_scroller.o src/qm_scroller.cpp

build/release/.obj/unix/qm_trayicon.o: src/qm_trayicon.cpp src/qm_trayicon.h \
		src/qm_widget_ids.h \
		src/qm_mpdcom.h \
		src/qm_config.h \
		src/qm_songinfo.h \
		src/qm_itemlist.h \
		src/qm_commandlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qm_trayicon.o src/qm_trayicon.cpp

build/release/.obj/unix/qm_settings.o: src/qm_settings.cpp src/qm_settings.h \
		src/qm_config.h \
		src/qm_mpdcom.h \
		src/qm_songinfo.h \
		src/qm_itemlist.h \
		src/qm_commandlist.h \
		src/qm_colorpicker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qm_settings.o src/qm_settings.cpp

build/release/.obj/unix/qm_browser.o: src/qm_browser.cpp src/qm_browser.h \
		src/qm_config.h \
		src/qm_browser_ids.h \
		src/qm_playlistview.h \
		src/qm_songinfo.h \
		src/qm_mpdcom.h \
		src/qm_itemlist.h \
		src/qm_commandlist.h \
		src/qm_libraryview.h \
		src/qm_streamloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qm_browser.o src/qm_browser.cpp

build/release/.obj/unix/qm_playlistview.o: src/qm_playlistview.cpp src/qm_playlistview.h \
		src/qm_songinfo.h \
		src/qm_mpdcom.h \
		src/qm_config.h \
		src/qm_itemlist.h \
		src/qm_commandlist.h \
		src/qm_browser_ids.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qm_playlistview.o src/qm_playlistview.cpp

build/release/.obj/unix/qm_libraryview.o: src/qm_libraryview.cpp src/qm_libraryview.h \
		src/qm_songinfo.h \
		src/qm_mpdcom.h \
		src/qm_config.h \
		src/qm_itemlist.h \
		src/qm_commandlist.h \
		src/qm_browser_ids.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qm_libraryview.o src/qm_libraryview.cpp

build/release/.obj/unix/qm_itemlist.o: src/qm_itemlist.cpp src/qm_itemlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qm_itemlist.o src/qm_itemlist.cpp

build/release/.obj/unix/qm_songinfo.o: src/qm_songinfo.cpp src/qm_songinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qm_songinfo.o src/qm_songinfo.cpp

build/release/.obj/unix/qm_streamloader.o: src/qm_streamloader.cpp src/qm_streamloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qm_streamloader.o src/qm_streamloader.cpp

build/release/.obj/unix/qm_colorpicker.o: src/qm_colorpicker.cpp src/qm_colorpicker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qm_colorpicker.o src/qm_colorpicker.cpp

build/release/.obj/unix/qtlocalpeer.o: src/qtlocalpeer.cpp src/qtlocalpeer.h \
		src/qtlockedfile.h \
		src/qtlockedfile.cpp \
		src/qtlockedfile_unix.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qtlocalpeer.o src/qtlocalpeer.cpp

build/release/.obj/unix/qtsingleapplication.o: src/qtsingleapplication.cpp src/qtsingleapplication.h \
		src/qtlocalpeer.h \
		src/qtlockedfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qtsingleapplication.o src/qtsingleapplication.cpp

build/release/.obj/unix/qrc_quimup.o: build/release/.rcc/qrc_quimup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/qrc_quimup.o build/release/.rcc/qrc_quimup.cpp

build/release/.obj/unix/moc_qm_clicklabel.o: build/release/.moc/moc_qm_clicklabel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/moc_qm_clicklabel.o build/release/.moc/moc_qm_clicklabel.cpp

build/release/.obj/unix/moc_qm_clickprogressbar.o: build/release/.moc/moc_qm_clickprogressbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/moc_qm_clickprogressbar.o build/release/.moc/moc_qm_clickprogressbar.cpp

build/release/.obj/unix/moc_qm_core.o: build/release/.moc/moc_qm_core.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/moc_qm_core.o build/release/.moc/moc_qm_core.cpp

build/release/.obj/unix/moc_qm_mpdcom.o: build/release/.moc/moc_qm_mpdcom.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/moc_qm_mpdcom.o build/release/.moc/moc_qm_mpdcom.cpp

build/release/.obj/unix/moc_qm_player.o: build/release/.moc/moc_qm_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/moc_qm_player.o build/release/.moc/moc_qm_player.cpp

build/release/.obj/unix/moc_qm_scroller.o: build/release/.moc/moc_qm_scroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/moc_qm_scroller.o build/release/.moc/moc_qm_scroller.cpp

build/release/.obj/unix/moc_qm_trayicon.o: build/release/.moc/moc_qm_trayicon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/moc_qm_trayicon.o build/release/.moc/moc_qm_trayicon.cpp

build/release/.obj/unix/moc_qm_settings.o: build/release/.moc/moc_qm_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/moc_qm_settings.o build/release/.moc/moc_qm_settings.cpp

build/release/.obj/unix/moc_qm_browser.o: build/release/.moc/moc_qm_browser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/moc_qm_browser.o build/release/.moc/moc_qm_browser.cpp

build/release/.obj/unix/moc_qm_playlistview.o: build/release/.moc/moc_qm_playlistview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/moc_qm_playlistview.o build/release/.moc/moc_qm_playlistview.cpp

build/release/.obj/unix/moc_qm_libraryview.o: build/release/.moc/moc_qm_libraryview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/moc_qm_libraryview.o build/release/.moc/moc_qm_libraryview.cpp

build/release/.obj/unix/moc_qm_streamloader.o: build/release/.moc/moc_qm_streamloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/moc_qm_streamloader.o build/release/.moc/moc_qm_streamloader.cpp

build/release/.obj/unix/moc_qm_colorpicker.o: build/release/.moc/moc_qm_colorpicker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/moc_qm_colorpicker.o build/release/.moc/moc_qm_colorpicker.cpp

build/release/.obj/unix/moc_qtlocalpeer.o: build/release/.moc/moc_qtlocalpeer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/moc_qtlocalpeer.o build/release/.moc/moc_qtlocalpeer.cpp

build/release/.obj/unix/moc_qtsingleapplication.o: build/release/.moc/moc_qtsingleapplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/unix/moc_qtsingleapplication.o build/release/.moc/moc_qtsingleapplication.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:


format:
	@-clang-format -i src/*
